version: '3'

services:
  site:
    container_name: site
    build:
      context: ./site
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 8877:8877
    networks:
      - rigby

networks:
  rigby:
    external: true
